# Generated by Django 6.1.1 on 2026-10-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
    ]
